apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  selector:
    app: java-service  # Issue 1: Wrong selector (doesn't match deployment)
  ports:
  - protocol: TCP
    port: 80  # Issue 2: Wrong port (should match app port 8080)
    targetPort: 8080
  type: ClusterIP  # Issue 3: Should be NodePort for external access
